### ISSUE TITLE
请问有更详细的readme吗？

### ISSUE THREAD

**Issue by tiandaoyuxi** [liumengniu/majiang-server#1]
D:\majiang-server>npm -i
npm <command>

Usage:

npm install        install all the dependencies in your project
npm install <foo>  add the <foo> dependency to your project
npm test           run this project's tests
npm run <foo>      run the script named <foo>
npm <command> -h   quick help on <command>
npm -l             display usage info for all commands
npm help <term>    search for help on <term> (in a browser)
npm help npm       more involved overview (in a browser)

All commands:

    access, adduser, audit, bugs, cache, ci, completion,
    config, dedupe, deprecate, diff, dist-tag, docs, doctor,
    edit, exec, explain, explore, find-dupes, fund, get, help,
    help-search, hook, init, install, install-ci-test,
    install-test, link, ll, login, logout, ls, org, outdated,
    owner, pack, ping, pkg, prefix, profile, prune, publish,
    query, rebuild, repo, restart, root, run-script, sbom,
    search, set, shrinkwrap, star, stars, start, stop, team,
    test, token, uninstall, unpublish, unstar, update, version,
    view, whoami

Specify configs in the ini-formatted file:
    C:\Users\win11\.npmrc
or on the command line via: npm <command> --key=value

More configuration info: npm help config
Configuration fields: npm help 7 config

npm@10.8.2 C:\Program Files\nodejs\node_modules\npm

D:\majiang-server> npm run start

> majiang-server@1.0.0 start
> nodemon index.js

'nodemon' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\majiang-server>

**Comment by liumengniu** [comment]
【npm -i】 改为 【npm i】，老兄，请仔细看文档，你多打了一个 【-】
